### ISSUE TITLE
When parsing a template, phong group hides

### ISSUE THREAD

**Issue by gortnarj** [Gira-X/VMT-Editor#35]
Phong brush, normal blend and probably all the new/refactored groups hide if the template doesn't have any related parameters.

**Comment by Gira-X** [comment]
So, opening a template keeps all unmodified (no parameter is changed) groups visible?

Because this applies to all groups, not just the new ones.

**Comment by Gira-X** [comment]
We could remove the call to `resetWidgets()` inside `openTemplate()` but this would keep all changed widgets.
An option?
