### ISSUE TITLE
Checking for updates returns Error creating SSL context 

### ISSUE THREAD

**Issue by gortnarj** [Gira-X/VMT-Editor#43]
![image](https://cloud.githubusercontent.com/assets/16923579/22678959/b3511a1c-ecfe-11e6-83bc-d7fd58a82433.png)

Can't reproduce on my computer

**Comment by Gira-X** [comment]
Solved by using the http link for the version: http://gortnar.com/vmt/version.txt

Not really sure how to fix the SSL error otherwise.
