### ISSUE TITLE
Add ability to preview vtf full size

### ISSUE THREAD

**Issue by gortnarj** [Gira-X/VMT-Editor#58]
Show a preview after 1 second of hover?

**Comment by Gira-X** [comment]
Should show the converted image in a standalone floating window:

Round down to nearest power of 2, or maybe make it scrollable?

![image](https://cloud.githubusercontent.com/assets/15002298/23616831/54305794-028b-11e7-9247-79f711025645.png)

**Comment by Gira-X** [comment]
Easier if the preview window is opened/closed by clicking instead.

**Comment by Gira-X** [comment]
http://stackoverflow.com/questions/38545799/remove-default-window-frame-border-of-non-client-area-on-windows-10
