### ISSUE TITLE
add support of "character" shader for csgo,PLZ

### ISSUE THREAD

**Issue by MineClever** [Gira-X/VMT-Editor#67]
csgo have a shader named "character",that can help to display a fake pbr effection.
- it should be a fixed version shader of Dota2

-------------------------------------------------------------------

and if a "VertexlitGeneric" shader with "$envmaplightscale" "1",should add "$envmaplightscaleminmax" "[float float]",or it will not work right in model with custom envmap

**Comment by gortnarj** [comment]
Considering how many people actually use `character`, its limited use and work needed to add it, it just isn't worth it right now, sorry. 

The light scale will be fixed in the next update.

**Comment by Gira-X** [comment]
light scale fixed!
