### ISSUE TITLE
$basealphaenvmapmask    is possibly a typo 

### ISSUE THREAD

**Issue by Reoxur** [Gira-X/VMT-Editor#68]
![VMT_Editor_2019-04-30_17-51-13](https://user-images.githubusercontent.com/37112810/56976820-14272980-6b74-11e9-969b-deb82b6dcc65.png)

I was struggling for an hour with this but someone pointed out  $basealphaenvmapmask  should actually be  $base**map**alphaenvmapmask.  Which is evident in the Valve Docs. Im sitll unsure though, but using  $basealphaenvmapmask  disabled my Envmap. 

![vivaldi_2019-04-30_18-17-36](https://user-images.githubusercontent.com/37112810/56976897-42a50480-6b74-11e9-916c-1ef66347e3cf.png)

**Comment by gortnarj** [comment]
`$basealphaenvmapmask` is correct, though the mask is inverted (VMT Editor shows it inverted for that reason) unless you're also using phong on models. If the parameter wasn't correct it wouldn't affect the envmap. Another issue may be if you're using 16 bit png files, where a bug in vtfcmd converts it as with no alpha channel.
