### ISSUE TITLE
Less depending to game

### ISSUE THREAD

**Issue by SupinePandora43** [Gira-X/VMT-Editor#70]
example from TF2:

1. i want to create/edit mod which replaces some textures
2. i open .vmt/vtf file (in `tf2/custom/(some mod folder)/materials`)
3. dialog `"(PATH TO TF2)/materials/(PATH TO VMT/VTF)" already exists. Do you want to overwrite or rename it?`

**Comment by gortnarj** [comment]
To fix this go to Games > Manage games and create a custom game with `<path to tf2>/custom/<mod folder>` path. To make it work add an empty file called `gameinfo.txt` into that directory.
