### ISSUE TITLE
Color slider issue

### ISSUE THREAD

**Issue by Number1S0n** [Gira-X/VMT-Editor#71]
I just got VMT editor mainly for Portal 2 and getting custom skins and stuff like that. I noticed that the color sliders do not surpass 16 where the max for Portal 2 is 255. Is there any way to change this?

**Comment by gortnarj** [comment]
Color sliders use normalized color values (0-1) so `$color "[1 1 1]"` is the same as `$color "{255 255 255}"`. 
You can change the slider to be higher than 1 because source also supports color values brighter than 255 255 255 white.
