### ISSUE TITLE
When opening an image file, pop up the convert to VTF dialog.

### ISSUE THREAD

**Issue by gortnarj** [Gira-X/VMT-Editor#8]

**Comment by Gira-X** [comment]
In other words, when an image file (jpg or png) is dragged onto the editor.exe, it should directly open the Convert to VTF dialog.

@gortnarj does this remove all the old code which sets the opened texture to $basetexture? Or should the old code be kept which places the VTF inside $basetexture?

**Comment by gortnarj** [comment]
Leave the code for VTF and remove the stuff for images.
